<?php  $this->layout('layout::default', ['title' => 'APOD']) ?>

<div class="jumbotron">
    <h1 class="text-center">Astronomy Picture of the Day App</h1>
    <p class="text-center">Images courtesy of <a style="color: #75B9ff;" href="http://apod.nasa.gov/apod/astropix.html">NASA</a></p>
</div>
<div id="gallery" class="row"></div>

<div class="text-center">
    <button id="more" class="btn btn-primary">More...</button><br /><br />
</div>

<div id="modal" class="modal fade">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 id="modal-title" class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <img id="modal-image" src="" alt="" class="img-responsive" />
            </div>
            <div class="modal-footer">
                <p id="modal-caption"></p>
            </div>
        </div>
    </div>
</div>

<?php $this->start('css') ?>
    <style type="text/css">
        body, html { background: #303030; color: white; }
        #modal { color: black; }
        #modal-caption { text-align: justify; }
        #gallery .thumb { border: 1px solid white; margin-bottom: 1.5em; }
    </style>
<?php $this->stop() ?>