<?php $this->layout('layout::default', ['title' => 'Innoo: Astronomy Picture of the Day']) ?>

<h1 class="text-center">Astronomy Picture of the Day</h1>
<p class="text-center">Images courtesy of <a style="color: #75B9ff;" href="http://apod.nasa.gov/apod/astropix.html">NASA</a></p>

<div id="gallery" class="row"></div>

<div class="text-center">
    <button id="more" class="btn btn-primary">More...</button><br /><br />
</div>

<div id="modal" class="modal fade" role="dialog" aria-labelledby="modal-title" aria-hidden="true">

    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
              <h4 id="modal-title" class="modal-title"></h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <img id="modal-image" src="" alt="" class="img-fluid" />
                <p id="modal-copy"></p>
            </div>
            <div class="modal-footer">
                <p id="modal-caption"></p>
            </div>
        </div>
    </div>
</div>

<?php $this->start('css') ?>
    <style type="text/css">
        body, html { background: #303030; color: white; }
        #modal { color: black; }
        #modal-caption { text-align: justify; }
        #gallery .thumb { border: 1px solid white; margin-bottom: 1.5em; }
    </style>
<?php $this->stop() ?>

<?php $this->start('javascript') ?>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script type="text/javascript">
        var requestInProgress = false;
        var currentPage = 0;
        function checkBottom() {
            if($(window).scrollTop() + $(window).height() > $(document).height() - 100) {
                $('#more').click();
            }
        }
        $(document).ready(function () {
            $(window).scroll(function () {
                checkBottom();
            });
            $('#more').click(function () {
                if (requestInProgress) return;
                requestInProgress = true;
                $.get('/picture-list/' + currentPage, function (data) {
                    if (data.length < 1) {
                        return;
                    }
                    currentPage++; requestInProgress = false;
                    $.each(data, function (date, picture) {
                        if (picture.media_type == 'image') {
                            $('#gallery').append([
                                '<div class="col-sm-6 col-md-4 col-lg-3 col-xl-2">',
                                    '<a id="' + date + '" href="' + picture.url + '" data-lightbox="gallery" data-title="Hello">',
                                        '<img src="' + picture.thumbnail_url + '" title="' + picture.title + '" class="img-fluid thumb" alt="" />',
                                    '</a>',
                                '</div>'
                            ].join(''));
                            $('#' + date).click(function (event) {
                                event.preventDefault();
                                $('#modal-title').text(picture.title);
                                if ("copyright" in picture) $('#modal-copy').text("Image Credits: " + picture.copyright);
                                $('#modal-image').attr('src', picture.url);
                                $('#modal-caption').text(picture.explanation);
                                $('#modal').modal();
                            });
                        }
                    });
                    checkBottom();
                });
            }).click();
        });
    </script>
<?php $this->stop() ?>